# Generated by Django 5.1.7 on 2025-03-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('converted_value', models.FloatField()),
                ('to_unit', models.CharField(max_length=10)),
            ],
        ),
    ]
